# Generated by Django 3.2.15 on 2022-09-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('movies', '0003_auto_20220907_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('role_type', models.CharField(choices=[('Director', 'Director'), ('Actor', 'Actor'), ('Producer', 'Producer')], max_length=100)),
                ('role_name', models.CharField(max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roless', to='persons.person')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='movie',
            name='casting',
            field=models.ManyToManyField(through='movies.Roles', to='persons.Person'),
        ),
    ]
