# Generated by Django 3.2.15 on 2022-09-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre_type',
        ),
    ]
