# Generated by Django 3.2.15 on 2022-09-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_movie_genre_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectgenre',
            name='s_movie',
        ),
    ]
