# Generated by Django 3.2.15 on 2022-09-09 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_selectgenre_s_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selectgenre',
            new_name='Genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_t',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='movies.genre'),
        ),
    ]
