# Generated by Django 3.2.15 on 2022-09-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20220909_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_t',
            new_name='genre_tttt',
        ),
    ]
