# Generated by Django 3.2.15 on 2022-09-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_rename_genre_t_movie_genre_tttt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_tttt',
            new_name='genre_t',
        ),
    ]
