# Generated by Django 3.2.15 on 2022-09-09 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_rename_genre_tttt_movie_genre_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre_t',
            field=models.OneToOneField(default='sin_genero', on_delete=django.db.models.deletion.CASCADE, to='movies.genre'),
        ),
    ]
