# Generated by Django 3.2.15 on 2022-09-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20220908_1857'),
        ('movies', '0018_alter_roles_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='casting',
            field=models.ManyToManyField(blank=True, through='movies.Roles', to='persons.Person'),
        ),
    ]
