# Generated by Django 3.2.15 on 2022-09-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('first_name', models.CharField(max_length=140)),
                ('last_name', models.CharField(max_length=140)),
                ('aliases', models.SlugField(max_length=40, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=True, max_length=20)),
                ('p_actor', models.BooleanField(default=False)),
                ('p_director', models.BooleanField(default=False)),
                ('p_productor', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.person')),
            ],
            options={
                'verbose_name': 'Actor',
            },
            bases=('persons.person',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.person')),
            ],
            options={
                'verbose_name': 'Director',
            },
            bases=('persons.person',),
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.person')),
            ],
            options={
                'verbose_name': 'Producer',
            },
            bases=('persons.person',),
        ),
        migrations.CreateModel(
            name='FemaleActor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('persons.actor',),
        ),
        migrations.CreateModel(
            name='MaleActor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('persons.actor',),
        ),
    ]
